name: rpipress-downloader
version: git
summary: Download RaspberryPi Press issues
description: |
  Download RaspberryPi Press issues.
  Freely available magazines are: Hackspace, HelloWorld, MagPi and Wireframe.
  You can choose to download all issues or only the latest one(s).
  Issues are save in $SNAP_USER_DATA/rpipress/{magazine}.
base: core20

grade: stable
confinement: strict

parts:
  downloaders:
    plugin: python
    source: .

apps:
  rpipress-downloader:
    command: bin/rpipress-downloader
    plugs: [home, network-bind, removable-media]
